site_name: Joshua Eckels website
site_url: https://eckelsjd.github.io/website/
site_author: Joshua Eckels
repo_name: eckelsjd/website
repo_url: https://github.com/eckelsjd/website
copyright: Copyright &copy 2024 Joshua Eckels

theme:
  name: material
  custom_dir: docs/templates
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: black
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: posts
      blog_toc: true
      categories_allowed:
        - Projects
        - Tutorials
        - Interesting

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eckelsjd
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eckelsjd
    - icon: fontawesome/regular/envelope
      link: mailto:eckelsjd@umich.edu
    - icon: fontawesome/solid/mug-hot
      link: https://buymeacoffee.com/joshuaeckels

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/about.css

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - About:
      - About: index.md
  - Projects:
      - Projects: projects.md
  - Posts:
      - posts/index.md
