site_name: Joshua Eckels website
site_url: https://eckelsjd.github.io/website/
site_author: Joshua Eckels
repo_name: eckelsjd/website
repo_url: https://github.com/eckelsjd/website.git
copyright: Copyright &copy 2024 Joshua Eckels

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eckelsjd
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eckelsjd
    - icon: fontawesome/regular/envelope
      link: mailto:eckelsjd@umich.edu
    - icon: fontawesome/solid/mug-hot
      link: https://buymeacoffee.com/joshuaeckels

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - About:
      - Home: about.md
  - Resume:
      - Resume: resume/resume.md
      - Research: resume/cv.md
      - Downloads: resume/downloads.md
  - Projects:
      - Home: projects.md
